[parity]
# No updates will be auto-installed
auto_update = "none"
base_path = "/mnt/disk1/data"
#no_persistent_txqueue = true #store pending tx
chain = "/etc/parity/spec.json"
#keys_path = "/etc/parity/keys"

[network]
# Parity will sync by downloading latest state first. Node will be operational in couple minutes.
bootnodes = ["enode://270410a8de0378337da37aedf5273ddcc573e1e414bbe28c1cfaf687a31295f3b740624fedbe5dd3ee532c910da18be48d9c41454a124b425c2c71b568a3d06e@10.154.0.2:30303"]
warp = true

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]
cors = ["*"]

[websockets]
disable = false
port = 8546
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"

[misc]
logging = "own_tx=trace"
log_file = "/var/log/parity.log"
color = true